version: '3.8'

services:
  backend:
    build:
      context: ./Back # Ruta al Dockerfile del backend
    container_name: backend
    ports:
      - "3000:3000" # Expone el backend en el puerto 3000
    networks:
      - pokemon-network

  frontend:
    build:
      context: ./Front # Ruta al Dockerfile del frontend
    container_name: frontend
    ports:
      - "8080:80" # Expone el frontend en el puerto 8080
    environment:
      BACKEND_URL: "http://backend:3000" # Apunta al servicio del backend
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
