apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: iad.ocir.io/idxyojfomq6q/backend:${BUILD_NUMBER} # Permite versionado dinámico
        ports:
        - containerPort: 3000
        resources: # Recurso recomendado para limitar uso de CPU/memoria
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe: # Asegura que el contenedor esté listo antes de recibir tráfico
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe: # Detecta y reinicia contenedores colgados
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets: # Referencia al Secret para OCIR
      - name: oci-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
